apiVersion: v1
kind: Service
metadata:
  name: ai-factory-server
  namespace: ai-factory
  labels:
    app: ai-factory-server
spec:
  type: ClusterIP
  selector:
    app: ai-factory-server
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
