apiVersion: v2
name: ai-factory
description: A Helm chart for ai-factory self-hosted service
type: application
version: 0.1.6
appVersion: "0.1.6"
keywords:
  - ai-factory
  - coding-agent
  - github-webhook
  - gitlab-webhook
home: https://github.com/Verdure-oss/ai-factory
maintainers:
  - name: verdure-oss
